- name: create swap /etc/rc.d/rc.local
  blockinfile:
    dest: /etc/rc.d/rc.local
    create: yes
    block: |
      dd if=/dev/zero of=/swapfile1 bs=1M count=2048
      chmod 600 /swapfile1
      mkswap /swapfile1
      swapon /swapfile1
      
- name: change swappiness
  sysctl:
    name: vm.swappiness
    value: 0
    state: present

- name: when swapfile1 exists
  stat:
    path: /swapfile1
  register: fm

- name: /swapfile1 not exist apply rc.local
  become_user: root
  shell: source /etc/rc.d/rc.local
  when: not fm.stat.exists

- name: insert swapfile /etc/fstab
  mount:
    name: swap
    src: /swapfile1
    fstype: swap
    opts: defaults
    passno: 0
    dump: 0
    state: present