---
- name: マスターノードの立上げ
  hosts: master
  become: true
  tasks:
  - name: create docker group
    group: name=docker
  - name: add a docker user
    user: name=docker password=docker123 group=docker state=present
  - name: install required packages
    yum: name={{ item }} state=present
    with_items:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
  - name: setup stable docker repository
    shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
    args:
      chdir: "/etc/yum.repos.d"
      creates: docker-ce.repo
  - name: install docker
    yum: name=docker-ce state=present
  - name: enable service docker
    systemd:
      name: docker
      enabled: yes
      state: started
  - name: install kubernetes's master etcd
    yum: name={{ item }} state=present
    with_items:
      - etcd
      - kubernetes-master
  - name: copy filesystem(diff file only)
    copy: src=master01/etc dest=/
  - name: enable service k8s
    systemd:
      name: kube-controller-manager
      enabled: yes
      state: started
  - name: enable service k8s
    systemd:
      name: kube-scheduler
      enabled: yes
      state: started
  - name: enable etcd
    systemd:
      name: etcd
      enabled: yes
      state: started
