---
- name: k8sで遊ぶためのCluster環境構築(master)
  hosts: master
  become: true
  roles:
    - docker
    - k8s-master

- name: k8sで遊ぶためのCluster環境構築(node)
  hosts: nodes
  become: true
  roles:
    - docker
    - k8s-node
