- name: install docker
  group: name=docker
- name: add a docker user
  user: name=docker password=docker123 group=docker state=present
- name: install required packages
  yum: name={{ item }} state=present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
- name: setup stable docker repository
  shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
  args:
    chdir: "/etc/yum.repos.d"
    creates: docker-ce.repo
- name: install docker
  #specific docker version and get docker-ce-selinux. but yum install docker-ce-selinux get docker-ce-latest, so add option --setopt=obsoletes=0
  shell: "yum install -y --setopt=obsoletes=0 docker-ce-17.03.1.ce-1.el7.centos docker-ce-selinux-17.03.1.ce-1.el7.centos"
- name: enable service docker
  systemd:
    name: docker
    enabled: yes
    state: started