- name: copy yum.repo
  copy: src=master01/yum-repo/kubernetes.repo dest=/etc/yum.repos.d/
- name: install kubernetes
  yum: name={{ item }} state=present
  with_items:
    - kubelet
    - kubeadm
    - kubectl
- name: cluster initialize
  script: init_kubeadm.sh
- name: node initialize
  shell: "{{ cluster_join }}"
