- name: debug register variable
  debug:
    var: hostvars['master01'].with_output['stdout_lines'][57]
- name: copy yum.repo
  copy: src=master01/yum-repo/kubernetes.repo dest=/etc/yum.repos.d/
- name: install kubernetes
  yum: name={{ item }} state=present
  with_items:
    - kubelet
    - kubeadm
    - kubectl
- name: cluster initialize
  script: init_kubeadm.sh
  ignore_errors: true # clean setup kubeadm reset error but no problem.
- name: enable service k8s
  systemd:
    name: kubelet
    enabled: yes
    state: started
- name: node initialize
  shell: "{{ hostvars['master01'].with_output['stdout_lines'][57] }}"
